services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/help-desk
      - JWT_SECRET=2e270779a074c58f892b6834921df57c806eeb448d3c3a36773d8e9b26f05dc68fe8e478aed873d079c1ae74ccdbad3143027983078b6a8192feef404f53c71b
      - APP_BASE_URL=https://helpdesk.yerliva.com
      - CORS_ORIGINS=https://helpdesk.yerliva.com
      - COOKIE_DOMAIN=https://helpdesk.yerliva.com
      - REDIS_URL=redis://redis:6379
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_USE_SSL=false
      - SMTP_HOST=mail.yerliva.com
      - SMTP_PORT=465
      - SMTP_SECURE=true
      - SMTP_USER=info@yerliva.com
      - SMTP_PASS=KMKngM2rQnh2P98HPtjh
      - SMTP_FROM=info@yerliva.com
      - SENTRY_DSN=https://d7a2f3993c2abf5a946497593368cb9a@o4511350922084352.ingest.de.sentry.io/451155490091835
      - LOG_LEVEL=info
    depends_on:
      - db
      - redis
      - minio

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=help-desk
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  redis_data:
  minio_data:
