/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthWhatsappRouteImport } from './routes/_auth/whatsapp'
import { Route as AuthUsersRouteImport } from './routes/_auth/users'
import { Route as AuthTenantsRouteImport } from './routes/_auth/tenants'
import { Route as AuthTasksRouteImport } from './routes/_auth/tasks'
import { Route as AuthSlaRouteImport } from './routes/_auth/sla'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthSearchRouteImport } from './routes/_auth/search'
import { Route as AuthRolesRouteImport } from './routes/_auth/roles'
import { Route as AuthReportsRouteImport } from './routes/_auth/reports'
import { Route as AuthProfileRouteImport } from './routes/_auth/profile'
import { Route as AuthOnboardingRouteImport } from './routes/_auth/onboarding'
import { Route as AuthNotificationsRouteImport } from './routes/_auth/notifications'
import { Route as AuthNotificationPreferencesRouteImport } from './routes/_auth/notification-preferences'
import { Route as AuthNotesRouteImport } from './routes/_auth/notes'
import { Route as AuthMessagesRouteImport } from './routes/_auth/messages'
import { Route as AuthMailboxesRouteImport } from './routes/_auth/mailboxes'
import { Route as AuthMacrosRouteImport } from './routes/_auth/macros'
import { Route as AuthGlobalUsersRouteImport } from './routes/_auth/global-users'
import { Route as AuthGlobalRolesRouteImport } from './routes/_auth/global-roles'
import { Route as AuthExportRouteImport } from './routes/_auth/export'
import { Route as AuthEmailTemplatesRouteImport } from './routes/_auth/email-templates'
import { Route as AuthDepartmentsRouteImport } from './routes/_auth/departments'
import { Route as AuthComplianceRouteImport } from './routes/_auth/compliance'
import { Route as AuthBillingRouteImport } from './routes/_auth/billing'
import { Route as AuthAutomationsRouteImport } from './routes/_auth/automations'
import { Route as AuthAuditLogsRouteImport } from './routes/_auth/audit-logs'
import { Route as AuthArchivedRouteImport } from './routes/_auth/archived'
import { Route as AuthApiTokensRouteImport } from './routes/_auth/api-tokens'
import { Route as AuthAccountSecurityRouteImport } from './routes/_auth/account-security'
import { Route as AuthTicketsIndexRouteImport } from './routes/_auth/tickets/index'
import { Route as AuthTicketsTicketIdRouteImport } from './routes/_auth/tickets/$ticketId'
import { Route as AuthTenantTenantIdRouteImport } from './routes/_auth/tenant.$tenantId'

const AuthDashboardLazyRouteImport = createFileRoute('/_auth/dashboard')()

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardLazyRoute = AuthDashboardLazyRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/dashboard.lazy').then((d) => d.Route),
)
const AuthWhatsappRoute = AuthWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUsersRoute = AuthUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTenantsRoute = AuthTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTasksRoute = AuthTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSlaRoute = AuthSlaRouteImport.update({
  id: '/sla',
  path: '/sla',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSearchRoute = AuthSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRolesRoute = AuthRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthRoute,
} as any)
const AuthReportsRoute = AuthReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthRoute,
} as any)
const AuthNotificationsRoute = AuthNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AuthRoute,
} as any)
const AuthNotificationPreferencesRoute =
  AuthNotificationPreferencesRouteImport.update({
    id: '/notification-preferences',
    path: '/notification-preferences',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthNotesRoute = AuthNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMessagesRoute = AuthMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMailboxesRoute = AuthMailboxesRouteImport.update({
  id: '/mailboxes',
  path: '/mailboxes',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMacrosRoute = AuthMacrosRouteImport.update({
  id: '/macros',
  path: '/macros',
  getParentRoute: () => AuthRoute,
} as any)
const AuthGlobalUsersRoute = AuthGlobalUsersRouteImport.update({
  id: '/global-users',
  path: '/global-users',
  getParentRoute: () => AuthRoute,
} as any)
const AuthGlobalRolesRoute = AuthGlobalRolesRouteImport.update({
  id: '/global-roles',
  path: '/global-roles',
  getParentRoute: () => AuthRoute,
} as any)
const AuthExportRoute = AuthExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEmailTemplatesRoute = AuthEmailTemplatesRouteImport.update({
  id: '/email-templates',
  path: '/email-templates',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDepartmentsRoute = AuthDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AuthRoute,
} as any)
const AuthComplianceRoute = AuthComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBillingRoute = AuthBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAutomationsRoute = AuthAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAuditLogsRoute = AuthAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AuthRoute,
} as any)
const AuthArchivedRoute = AuthArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => AuthRoute,
} as any)
const AuthApiTokensRoute = AuthApiTokensRouteImport.update({
  id: '/api-tokens',
  path: '/api-tokens',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAccountSecurityRoute = AuthAccountSecurityRouteImport.update({
  id: '/account-security',
  path: '/account-security',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTicketsIndexRoute = AuthTicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTicketsTicketIdRoute = AuthTicketsTicketIdRouteImport.update({
  id: '/tickets/$ticketId',
  path: '/tickets/$ticketId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTenantTenantIdRoute = AuthTenantTenantIdRouteImport.update({
  id: '/tenant/$tenantId',
  path: '/tenant/$tenantId',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/account-security': typeof AuthAccountSecurityRoute
  '/api-tokens': typeof AuthApiTokensRoute
  '/archived': typeof AuthArchivedRoute
  '/audit-logs': typeof AuthAuditLogsRoute
  '/automations': typeof AuthAutomationsRoute
  '/billing': typeof AuthBillingRoute
  '/compliance': typeof AuthComplianceRoute
  '/departments': typeof AuthDepartmentsRoute
  '/email-templates': typeof AuthEmailTemplatesRoute
  '/export': typeof AuthExportRoute
  '/global-roles': typeof AuthGlobalRolesRoute
  '/global-users': typeof AuthGlobalUsersRoute
  '/macros': typeof AuthMacrosRoute
  '/mailboxes': typeof AuthMailboxesRoute
  '/messages': typeof AuthMessagesRoute
  '/notes': typeof AuthNotesRoute
  '/notification-preferences': typeof AuthNotificationPreferencesRoute
  '/notifications': typeof AuthNotificationsRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/profile': typeof AuthProfileRoute
  '/reports': typeof AuthReportsRoute
  '/roles': typeof AuthRolesRoute
  '/search': typeof AuthSearchRoute
  '/settings': typeof AuthSettingsRoute
  '/sla': typeof AuthSlaRoute
  '/tasks': typeof AuthTasksRoute
  '/tenants': typeof AuthTenantsRoute
  '/users': typeof AuthUsersRoute
  '/whatsapp': typeof AuthWhatsappRoute
  '/dashboard': typeof AuthDashboardLazyRoute
  '/tenant/$tenantId': typeof AuthTenantTenantIdRoute
  '/tickets/$ticketId': typeof AuthTicketsTicketIdRoute
  '/tickets/': typeof AuthTicketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/account-security': typeof AuthAccountSecurityRoute
  '/api-tokens': typeof AuthApiTokensRoute
  '/archived': typeof AuthArchivedRoute
  '/audit-logs': typeof AuthAuditLogsRoute
  '/automations': typeof AuthAutomationsRoute
  '/billing': typeof AuthBillingRoute
  '/compliance': typeof AuthComplianceRoute
  '/departments': typeof AuthDepartmentsRoute
  '/email-templates': typeof AuthEmailTemplatesRoute
  '/export': typeof AuthExportRoute
  '/global-roles': typeof AuthGlobalRolesRoute
  '/global-users': typeof AuthGlobalUsersRoute
  '/macros': typeof AuthMacrosRoute
  '/mailboxes': typeof AuthMailboxesRoute
  '/messages': typeof AuthMessagesRoute
  '/notes': typeof AuthNotesRoute
  '/notification-preferences': typeof AuthNotificationPreferencesRoute
  '/notifications': typeof AuthNotificationsRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/profile': typeof AuthProfileRoute
  '/reports': typeof AuthReportsRoute
  '/roles': typeof AuthRolesRoute
  '/search': typeof AuthSearchRoute
  '/settings': typeof AuthSettingsRoute
  '/sla': typeof AuthSlaRoute
  '/tasks': typeof AuthTasksRoute
  '/tenants': typeof AuthTenantsRoute
  '/users': typeof AuthUsersRoute
  '/whatsapp': typeof AuthWhatsappRoute
  '/dashboard': typeof AuthDashboardLazyRoute
  '/tenant/$tenantId': typeof AuthTenantTenantIdRoute
  '/tickets/$ticketId': typeof AuthTicketsTicketIdRoute
  '/tickets': typeof AuthTicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_auth/account-security': typeof AuthAccountSecurityRoute
  '/_auth/api-tokens': typeof AuthApiTokensRoute
  '/_auth/archived': typeof AuthArchivedRoute
  '/_auth/audit-logs': typeof AuthAuditLogsRoute
  '/_auth/automations': typeof AuthAutomationsRoute
  '/_auth/billing': typeof AuthBillingRoute
  '/_auth/compliance': typeof AuthComplianceRoute
  '/_auth/departments': typeof AuthDepartmentsRoute
  '/_auth/email-templates': typeof AuthEmailTemplatesRoute
  '/_auth/export': typeof AuthExportRoute
  '/_auth/global-roles': typeof AuthGlobalRolesRoute
  '/_auth/global-users': typeof AuthGlobalUsersRoute
  '/_auth/macros': typeof AuthMacrosRoute
  '/_auth/mailboxes': typeof AuthMailboxesRoute
  '/_auth/messages': typeof AuthMessagesRoute
  '/_auth/notes': typeof AuthNotesRoute
  '/_auth/notification-preferences': typeof AuthNotificationPreferencesRoute
  '/_auth/notifications': typeof AuthNotificationsRoute
  '/_auth/onboarding': typeof AuthOnboardingRoute
  '/_auth/profile': typeof AuthProfileRoute
  '/_auth/reports': typeof AuthReportsRoute
  '/_auth/roles': typeof AuthRolesRoute
  '/_auth/search': typeof AuthSearchRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/sla': typeof AuthSlaRoute
  '/_auth/tasks': typeof AuthTasksRoute
  '/_auth/tenants': typeof AuthTenantsRoute
  '/_auth/users': typeof AuthUsersRoute
  '/_auth/whatsapp': typeof AuthWhatsappRoute
  '/_auth/dashboard': typeof AuthDashboardLazyRoute
  '/_auth/tenant/$tenantId': typeof AuthTenantTenantIdRoute
  '/_auth/tickets/$ticketId': typeof AuthTicketsTicketIdRoute
  '/_auth/tickets/': typeof AuthTicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/changelog'
    | '/contact'
    | '/docs'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/security'
    | '/terms'
    | '/verify-email'
    | '/account-security'
    | '/api-tokens'
    | '/archived'
    | '/audit-logs'
    | '/automations'
    | '/billing'
    | '/compliance'
    | '/departments'
    | '/email-templates'
    | '/export'
    | '/global-roles'
    | '/global-users'
    | '/macros'
    | '/mailboxes'
    | '/messages'
    | '/notes'
    | '/notification-preferences'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/reports'
    | '/roles'
    | '/search'
    | '/settings'
    | '/sla'
    | '/tasks'
    | '/tenants'
    | '/users'
    | '/whatsapp'
    | '/dashboard'
    | '/tenant/$tenantId'
    | '/tickets/$ticketId'
    | '/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/changelog'
    | '/contact'
    | '/docs'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/security'
    | '/terms'
    | '/verify-email'
    | '/account-security'
    | '/api-tokens'
    | '/archived'
    | '/audit-logs'
    | '/automations'
    | '/billing'
    | '/compliance'
    | '/departments'
    | '/email-templates'
    | '/export'
    | '/global-roles'
    | '/global-users'
    | '/macros'
    | '/mailboxes'
    | '/messages'
    | '/notes'
    | '/notification-preferences'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/reports'
    | '/roles'
    | '/search'
    | '/settings'
    | '/sla'
    | '/tasks'
    | '/tenants'
    | '/users'
    | '/whatsapp'
    | '/dashboard'
    | '/tenant/$tenantId'
    | '/tickets/$ticketId'
    | '/tickets'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/accept-invite'
    | '/changelog'
    | '/contact'
    | '/docs'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/security'
    | '/terms'
    | '/verify-email'
    | '/_auth/account-security'
    | '/_auth/api-tokens'
    | '/_auth/archived'
    | '/_auth/audit-logs'
    | '/_auth/automations'
    | '/_auth/billing'
    | '/_auth/compliance'
    | '/_auth/departments'
    | '/_auth/email-templates'
    | '/_auth/export'
    | '/_auth/global-roles'
    | '/_auth/global-users'
    | '/_auth/macros'
    | '/_auth/mailboxes'
    | '/_auth/messages'
    | '/_auth/notes'
    | '/_auth/notification-preferences'
    | '/_auth/notifications'
    | '/_auth/onboarding'
    | '/_auth/profile'
    | '/_auth/reports'
    | '/_auth/roles'
    | '/_auth/search'
    | '/_auth/settings'
    | '/_auth/sla'
    | '/_auth/tasks'
    | '/_auth/tenants'
    | '/_auth/users'
    | '/_auth/whatsapp'
    | '/_auth/dashboard'
    | '/_auth/tenant/$tenantId'
    | '/_auth/tickets/$ticketId'
    | '/_auth/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  ChangelogRoute: typeof ChangelogRoute
  ContactRoute: typeof ContactRoute
  DocsRoute: typeof DocsRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SecurityRoute: typeof SecurityRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/whatsapp': {
      id: '/_auth/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AuthWhatsappRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/users': {
      id: '/_auth/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthUsersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tenants': {
      id: '/_auth/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof AuthTenantsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tasks': {
      id: '/_auth/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthTasksRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sla': {
      id: '/_auth/sla'
      path: '/sla'
      fullPath: '/sla'
      preLoaderRoute: typeof AuthSlaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/search': {
      id: '/_auth/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthSearchRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/roles': {
      id: '/_auth/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthRolesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reports': {
      id: '/_auth/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthReportsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/onboarding': {
      id: '/_auth/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthOnboardingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/notifications': {
      id: '/_auth/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthNotificationsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/notification-preferences': {
      id: '/_auth/notification-preferences'
      path: '/notification-preferences'
      fullPath: '/notification-preferences'
      preLoaderRoute: typeof AuthNotificationPreferencesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/notes': {
      id: '/_auth/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthNotesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/messages': {
      id: '/_auth/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthMessagesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/mailboxes': {
      id: '/_auth/mailboxes'
      path: '/mailboxes'
      fullPath: '/mailboxes'
      preLoaderRoute: typeof AuthMailboxesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/macros': {
      id: '/_auth/macros'
      path: '/macros'
      fullPath: '/macros'
      preLoaderRoute: typeof AuthMacrosRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/global-users': {
      id: '/_auth/global-users'
      path: '/global-users'
      fullPath: '/global-users'
      preLoaderRoute: typeof AuthGlobalUsersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/global-roles': {
      id: '/_auth/global-roles'
      path: '/global-roles'
      fullPath: '/global-roles'
      preLoaderRoute: typeof AuthGlobalRolesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/export': {
      id: '/_auth/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof AuthExportRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/email-templates': {
      id: '/_auth/email-templates'
      path: '/email-templates'
      fullPath: '/email-templates'
      preLoaderRoute: typeof AuthEmailTemplatesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/departments': {
      id: '/_auth/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AuthDepartmentsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/compliance': {
      id: '/_auth/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof AuthComplianceRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/billing': {
      id: '/_auth/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthBillingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/automations': {
      id: '/_auth/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AuthAutomationsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/audit-logs': {
      id: '/_auth/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuthAuditLogsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/archived': {
      id: '/_auth/archived'
      path: '/archived'
      fullPath: '/archived'
      preLoaderRoute: typeof AuthArchivedRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/api-tokens': {
      id: '/_auth/api-tokens'
      path: '/api-tokens'
      fullPath: '/api-tokens'
      preLoaderRoute: typeof AuthApiTokensRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/account-security': {
      id: '/_auth/account-security'
      path: '/account-security'
      fullPath: '/account-security'
      preLoaderRoute: typeof AuthAccountSecurityRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tickets/': {
      id: '/_auth/tickets/'
      path: '/tickets'
      fullPath: '/tickets/'
      preLoaderRoute: typeof AuthTicketsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tickets/$ticketId': {
      id: '/_auth/tickets/$ticketId'
      path: '/tickets/$ticketId'
      fullPath: '/tickets/$ticketId'
      preLoaderRoute: typeof AuthTicketsTicketIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tenant/$tenantId': {
      id: '/_auth/tenant/$tenantId'
      path: '/tenant/$tenantId'
      fullPath: '/tenant/$tenantId'
      preLoaderRoute: typeof AuthTenantTenantIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAccountSecurityRoute: typeof AuthAccountSecurityRoute
  AuthApiTokensRoute: typeof AuthApiTokensRoute
  AuthArchivedRoute: typeof AuthArchivedRoute
  AuthAuditLogsRoute: typeof AuthAuditLogsRoute
  AuthAutomationsRoute: typeof AuthAutomationsRoute
  AuthBillingRoute: typeof AuthBillingRoute
  AuthComplianceRoute: typeof AuthComplianceRoute
  AuthDepartmentsRoute: typeof AuthDepartmentsRoute
  AuthEmailTemplatesRoute: typeof AuthEmailTemplatesRoute
  AuthExportRoute: typeof AuthExportRoute
  AuthGlobalRolesRoute: typeof AuthGlobalRolesRoute
  AuthGlobalUsersRoute: typeof AuthGlobalUsersRoute
  AuthMacrosRoute: typeof AuthMacrosRoute
  AuthMailboxesRoute: typeof AuthMailboxesRoute
  AuthMessagesRoute: typeof AuthMessagesRoute
  AuthNotesRoute: typeof AuthNotesRoute
  AuthNotificationPreferencesRoute: typeof AuthNotificationPreferencesRoute
  AuthNotificationsRoute: typeof AuthNotificationsRoute
  AuthOnboardingRoute: typeof AuthOnboardingRoute
  AuthProfileRoute: typeof AuthProfileRoute
  AuthReportsRoute: typeof AuthReportsRoute
  AuthRolesRoute: typeof AuthRolesRoute
  AuthSearchRoute: typeof AuthSearchRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthSlaRoute: typeof AuthSlaRoute
  AuthTasksRoute: typeof AuthTasksRoute
  AuthTenantsRoute: typeof AuthTenantsRoute
  AuthUsersRoute: typeof AuthUsersRoute
  AuthWhatsappRoute: typeof AuthWhatsappRoute
  AuthDashboardLazyRoute: typeof AuthDashboardLazyRoute
  AuthTenantTenantIdRoute: typeof AuthTenantTenantIdRoute
  AuthTicketsTicketIdRoute: typeof AuthTicketsTicketIdRoute
  AuthTicketsIndexRoute: typeof AuthTicketsIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAccountSecurityRoute: AuthAccountSecurityRoute,
  AuthApiTokensRoute: AuthApiTokensRoute,
  AuthArchivedRoute: AuthArchivedRoute,
  AuthAuditLogsRoute: AuthAuditLogsRoute,
  AuthAutomationsRoute: AuthAutomationsRoute,
  AuthBillingRoute: AuthBillingRoute,
  AuthComplianceRoute: AuthComplianceRoute,
  AuthDepartmentsRoute: AuthDepartmentsRoute,
  AuthEmailTemplatesRoute: AuthEmailTemplatesRoute,
  AuthExportRoute: AuthExportRoute,
  AuthGlobalRolesRoute: AuthGlobalRolesRoute,
  AuthGlobalUsersRoute: AuthGlobalUsersRoute,
  AuthMacrosRoute: AuthMacrosRoute,
  AuthMailboxesRoute: AuthMailboxesRoute,
  AuthMessagesRoute: AuthMessagesRoute,
  AuthNotesRoute: AuthNotesRoute,
  AuthNotificationPreferencesRoute: AuthNotificationPreferencesRoute,
  AuthNotificationsRoute: AuthNotificationsRoute,
  AuthOnboardingRoute: AuthOnboardingRoute,
  AuthProfileRoute: AuthProfileRoute,
  AuthReportsRoute: AuthReportsRoute,
  AuthRolesRoute: AuthRolesRoute,
  AuthSearchRoute: AuthSearchRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthSlaRoute: AuthSlaRoute,
  AuthTasksRoute: AuthTasksRoute,
  AuthTenantsRoute: AuthTenantsRoute,
  AuthUsersRoute: AuthUsersRoute,
  AuthWhatsappRoute: AuthWhatsappRoute,
  AuthDashboardLazyRoute: AuthDashboardLazyRoute,
  AuthTenantTenantIdRoute: AuthTenantTenantIdRoute,
  AuthTicketsTicketIdRoute: AuthTicketsTicketIdRoute,
  AuthTicketsIndexRoute: AuthTicketsIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  ChangelogRoute: ChangelogRoute,
  ContactRoute: ContactRoute,
  DocsRoute: DocsRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SecurityRoute: SecurityRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
